// Code generated by protoc-gen-go.
// source: netmessageid.proto
// DO NOT EDIT!

/*
Package onepiece is a generated protocol buffer package.

It is generated from these files:
	netmessageid.proto
	sayhi.proto

It has these top-level messages:
	SayHiRequest
	SayHiResponse
*/
package onepiece

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type NetMsgID int32

const (
	NetMsgID_UNKNOWN          NetMsgID = 0
	NetMsgID_SAYHI            NetMsgID = 100
	NetMsgID_ERROR            NetMsgID = 101
	NetMsgID_HEART_BEAT       NetMsgID = 102
	NetMsgID_REGISTER         NetMsgID = 103
	NetMsgID_AUTO_REGISTER    NetMsgID = 104
	NetMsgID_LOGIN            NetMsgID = 105
	NetMsgID_ENCRYPT          NetMsgID = 106
	NetMsgID_LOGIN_WORLD      NetMsgID = 107
	NetMsgID_CREATE_ROLE      NetMsgID = 108
	NetMsgID_RANDOM_ROLE_NAME NetMsgID = 109
	NetMsgID_DELETE_ROLE      NetMsgID = 110
	NetMsgID_CHOOSE_ROLE      NetMsgID = 111
)

var NetMsgID_name = map[int32]string{
	0:   "UNKNOWN",
	100: "SAYHI",
	101: "ERROR",
	102: "HEART_BEAT",
	103: "REGISTER",
	104: "AUTO_REGISTER",
	105: "LOGIN",
	106: "ENCRYPT",
	107: "LOGIN_WORLD",
	108: "CREATE_ROLE",
	109: "RANDOM_ROLE_NAME",
	110: "DELETE_ROLE",
	111: "CHOOSE_ROLE",
}
var NetMsgID_value = map[string]int32{
	"UNKNOWN":          0,
	"SAYHI":            100,
	"ERROR":            101,
	"HEART_BEAT":       102,
	"REGISTER":         103,
	"AUTO_REGISTER":    104,
	"LOGIN":            105,
	"ENCRYPT":          106,
	"LOGIN_WORLD":      107,
	"CREATE_ROLE":      108,
	"RANDOM_ROLE_NAME": 109,
	"DELETE_ROLE":      110,
	"CHOOSE_ROLE":      111,
}

func (x NetMsgID) String() string {
	return proto.EnumName(NetMsgID_name, int32(x))
}

func init() {
	proto.RegisterEnum("onepiece.NetMsgID", NetMsgID_name, NetMsgID_value)
}
