// Code generated by protoc-gen-go.
// source: sayhi.proto
// DO NOT EDIT!

package onepiece

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type SayHiRequest struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (m *SayHiRequest) Reset()         { *m = SayHiRequest{} }
func (m *SayHiRequest) String() string { return proto.CompactTextString(m) }
func (*SayHiRequest) ProtoMessage()    {}

type SayHiResponse struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (m *SayHiResponse) Reset()         { *m = SayHiResponse{} }
func (m *SayHiResponse) String() string { return proto.CompactTextString(m) }
func (*SayHiResponse) ProtoMessage()    {}

func init() {
	proto.RegisterType((*SayHiRequest)(nil), "onepiece.SayHiRequest")
	proto.RegisterType((*SayHiResponse)(nil), "onepiece.SayHiResponse")
}
